spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mariadb.default:3306/MINI_PROJECT_01_DB
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

plan-api:
  messages:
    planSaveSucc: Plan Saved Successfully ðŸ˜ƒ
    planSaveFail: Plan Failed to SaveðŸ˜¥
    PlanUpdateSucc: Plan Updated Successfully ðŸ˜ƒ
    PlanUpdateFail: Plan Failed to Update ðŸ˜¥
    PlanDeleteSucc: Plan Deleted Successfully ðŸ˜ƒ
    PlanDeleteFail: Plan Failed to Delete ðŸ˜¥
    PlanStatusChangeSuccc: Plan Status Changed Successfully ðŸ˜ƒ
    PlanStatusChageFail: Plan Status Change Failed ðŸ˜¥
